services:
  arbi-tr-api-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arbi-tr-api-container
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN:-}
      - WHISPER_DEVICE=${WHISPER_DEVICE:-}
      - DIARIZE_DEVICE=${DIARIZE_DEVICE:-}
      - WHISPER_BATCH_SIZE=${WHISPER_BATCH_SIZE:-}
      - PYANNOTE_SEG_BATCH=${PYANNOTE_SEG_BATCH:-}
      - PYANNOTE_EMB_BATCH=${PYANNOTE_EMB_BATCH:-}
      - ENABLE_TF32=${ENABLE_TF32:-}
    volumes:
      - ${HF_CACHE:-~/.cache/huggingface}:/app/models
    runtime: nvidia
    networks:
      - backend

  arbi-tr-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arbi-tr-frontend-container
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=1000
      - API_ENDPOINT=http://arbi-tr-api-container:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge
