version: '3.8'

services:
  cert-init:
    build:
      context: ./cert-gen
      dockerfile: Dockerfile
    volumes:
      - certs:/certs
    restart: unless-stopped
    networks:
      - backend

  arbi-tr-api-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arbi-tr-api-container
    depends_on:
      - cert-init
    ports:
      - "8001:8000"
    environment:
      - USE_MTLS=1
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HOME=/app/models
    volumes:
      - /mnt/k8scache/:/app/models
      - certs:/app/certs   # Mount the certs volume to /app/certs
    runtime: nvidia
    networks:
      - backend

  arbi-tr-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arbi-tr-frontend-container
    ports:
      - "8501:8501"
    depends_on:
      - cert-init
    environment:
      - USE_MTLS=1
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=1000
      - API_ENDPOINT=https://arbi-tr-api-container:8000
    volumes:
      - certs:/app/certs   # Mount the certs volume to /app/certs
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  certs:
