version: '3.8'

services:
  arbi-tr-api-service:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: arbi-tr-api-container
    image: arbidev/arbi-tr:latest # Specify your Docker image and version
    command: [] # Add any startup command or arguments if needed
    ports:
      - "8000:8000" # Map port 8000 of the host to port 8000 of the container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Use all available GPUs
      - HF_HOME=/app/models
    volumes:
      - /mnt/k8scache/stt/:/app/models
    runtime: nvidia # Use the NVIDIA runtime for GPU support
  arbi-tr-frontend:
    build:
      context: ./frontend # Directory containing the frontend Dockerfile
      dockerfile: Dockerfile 
    container_name: arbi-tr-frontend-container
    image: arbidev/arbi-tr-frontend:latest
    ports:
      - "8501:8501" # Expose port 8501 on the host and map it to port 8501 in the container
    environment: {}
      # If there are any environment variables needed, specify them here
    restart: always
