# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_processing.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61udio_processing.proto\x12\x0f\x61udioProcessing\"\x80\x01\n\x0c\x41udioRequest\x12,\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x1b.audioProcessing.AudioChunkH\x00\x12\x32\n\x08settings\x18\x02 \x01(\x0b\x32\x1e.audioProcessing.AudioSettingsH\x00\x42\x0e\n\x0crequest_data\"e\n\rAudioSettings\x12\x15\n\rsize_of_model\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x17\n\x0fsource_language\x18\x03 \x01(\t\x12\x16\n\x0espeaker_number\x18\x04 \x01(\x05\"\x1d\n\nAudioChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\"\n\x0fProcessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0eResultsRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"=\n\x0fResultsResponse\x12*\n\x08segments\x18\x01 \x03(\x0b\x32\x18.audioProcessing.Segment\"D\n\x07Segment\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\x12\x0f\n\x07speaker\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t2\xbc\x01\n\x16\x41udioProcessingService\x12Q\n\x0cProcessAudio\x12\x1d.audioProcessing.AudioRequest\x1a .audioProcessing.ProcessResponse(\x01\x12O\n\nGetResults\x12\x1f.audioProcessing.ResultsRequest\x1a .audioProcessing.ResultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=44
  _globals['_AUDIOREQUEST']._serialized_end=172
  _globals['_AUDIOSETTINGS']._serialized_start=174
  _globals['_AUDIOSETTINGS']._serialized_end=275
  _globals['_AUDIOCHUNK']._serialized_start=277
  _globals['_AUDIOCHUNK']._serialized_end=306
  _globals['_PROCESSRESPONSE']._serialized_start=308
  _globals['_PROCESSRESPONSE']._serialized_end=342
  _globals['_RESULTSREQUEST']._serialized_start=344
  _globals['_RESULTSREQUEST']._serialized_end=379
  _globals['_RESULTSRESPONSE']._serialized_start=381
  _globals['_RESULTSRESPONSE']._serialized_end=442
  _globals['_SEGMENT']._serialized_start=444
  _globals['_SEGMENT']._serialized_end=512
  _globals['_AUDIOPROCESSINGSERVICE']._serialized_start=515
  _globals['_AUDIOPROCESSINGSERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
